# Generated by Django 5.0.4 on 2024-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_institution_certificates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'ordering': ['-issu_date']},
        ),
        migrations.AddField(
            model_name='certificates',
            name='issu_date',
            field=models.DateTimeField(null=True),
        ),
    ]
