# Generated by Django 5.0.4 on 2024-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_certificates_options_certificates_issu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='field_name',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
