# Generated by Django 5.0.4 on 2024-04-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
