# Generated by Django 5.0.4 on 2024-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_home',
            field=models.ImageField(default='blog/default.jpg', upload_to='blog/'),
        ),
    ]
